version: '3'

services:

    php:
        build:
            context: ./
            args:
                - ver=dev
                - network=${NETWORK}
                - domain=localhost
                - domain_file=localhost
                - email=${EMAIL}
                - container_prefix=${CONTAINER_PREFIX}
            dockerfile: _docker/dev/app/Dockerfile
        restart: always
        volumes:
            - ./src:/var/www/html
            - ./_docker/dev/apache/log/:/var/log/apache2/
            - ./_docker/dev/apache/localhost.conf:/etc/apache2/sites-available/000-default.conf
        container_name: ${CONTAINER_PREFIX}_php
        ports:
            - ${APP_PORT}:80
        depends_on:
            - db

    db:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            #- /var/db:/var/lib/mysql
            - ./tmp/db:/var/lib/mysql
            - ./_docker/dev/mysql/log/:/var/log/mysql
            - ./_docker/dev/mysql/conf.d/:/etc/mysql/conf.d
            - ./_docker/dev/mysql/my.cnf:/etc/my.cnf
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --general-log-file=/var/lib/mysql/general-log.log
        ports:
            - "${DB_PORT}:3306"
        container_name: ${CONTAINER_PREFIX}_db

    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - "${PHPMYADMIN_PORT}:80"
        links:
            - "db:db"
        environment:
            - PMA_HOST=${DB_DATABASE}
            - UPLOAD_LIMIT=2048M
        container_name: ${CONTAINER_PREFIX}_phpmyadmin

    smtp:
        image: namshi/smtp
        environment:
            - SMARTHOST_ADDRESS=test@test.ru
            - SMARTHOST_PORT=587
            - SMARTHOST_USER=69ad74a3d4934b39b6e1
            - SMARTHOST_PASSWORD=2624a4326d34457787ee490731357e6b
            - SMARTHOST_ALIASES=smtp.mailspons.com


